### ISSUE TITLE
Wolfgang all data missing

### ISSUE THREAD

**Issue by ff6347** [FH-Potsdam/steel-ant-io-data.json#10]

**Comment by wollemannone** [comment]
Hi Fabian,

habe meine Daten jetzt in die richitge JSON eingetragen. Auf der Seite
erscheinen sie aber irgendwie trotzdem nicht. Musst du das händisch
updaten oder ist immernoch was falsch mit miener Eingabe?

Viele Grüße

**Comment by ff6347** [comment]
Yes. Das update mache ich von Hand. Nicht alles ist automatisiert bei mir. :-)
