### ISSUE TITLE
http://dustinkummer.com/ not allowed

### ISSUE THREAD

**Issue by ff6347** [FH-Potsdam/steel-ant-io-data.json#19]

**Comment by ff6347** [comment]
http://dustinkummer.com/ is not allowed what should I use as contact instead?

**Comment by miduku** [comment]
Yeah, I haven't finished my website yet... Use my github page instead then. https://github.com/miduku

**Comment by ff6347** [comment]
Roger. Roger.

**Comment by ff6347** [comment]
ähm. There is no public mail adress on your github account

**Comment by miduku** [comment]
Now there is :)

**Comment by ff6347** [comment]
roger roger.

**Comment by ff6347** [comment]
BTW. I suggest adding at least a splash image or a basic index.html to your domain

**Comment by miduku** [comment]
Yea i know. I just didn't get to that yet. The days went by, other things had to be done and then I forgot... :P. Same ol' dilemma.

**Comment by ff6347** [comment]
:-)
